runtime: python

runtime_config:
    operating_system: "ubuntu22"

env: flex
entrypoint: gunicorn -b :$PORT elia.wsgi

instance_class: F1  # F1 instances are eligible for free tier

env_variables:
  # Add environment variables if necessary
  DEBUG: "True"
